spring:
  security:
    user:
      name: brad
      password: 12345
  application:
    name: security-basic
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:spring-security}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12341234}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
logging:
  level:
    org:
      springframework:
        security: TRACE
  pattern:
    console:
      ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


